### ISSUE TITLE
Access token publicly visible in src/utils/geocode.js

### ISSUE THREAD

**Issue by typedashutosh** [MrStrange124/weather-app#1]
**SECURITY ISSUE**
https://github.com/MrStrange124/weather-app/blob/7c7fd1c3aafb44d6039000c0604649b69180e6a1/src/utils/geocode.js#L5

**Comment by MrStrange124** [comment]
fixed.

**Comment by typedashutosh** [comment]
Access tokens and keys should be kept in `.env` files and then, they are accessible through `process.env.TOKEN` 
Learn more at https://robertcooper.me/post/front-end-javascript-environment-variables
